version: '3.2'
services:
    mongodb:
        image: mongo
        ports:
            - '27017:27017'

    backend:
        container_name: cct_backend
        build:
            context: .
            dockerfile: ./server/gcloud.Dockerfile
        ports:
            - '3001:3001'
        volumes:
            # use everything in /server for /app/
            - './server:/usr/src/app/'
            # use node_modules from app
            - '/usr/src/app/node_modules'
        depends_on:
            - mongodb
        links:
            - mongodb

    frontend:
        container_name: cct_frontend
        build:
            context: .
            dockerfile: ./client/gcloud.Dockerfile
        volumes:
            - './client:/usr/src/app'
            - '/usr/src/app/node_modules'
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=development
        depends_on:
            - backend
        
            